### ISSUE TITLE
建议增加几条规则

### ISSUE THREAD

**Issue by alexhua** [huanz/surge-hosts#1]
```
#!MANAGED-CONFIG http://surge.w3cboy.com/CMCC.conf interval=86400
```

Surge 现在支持远程自动更新config了 86400s表示间隔24小时更新一次

`dns-server = 8.8.4.4, 8.8.8.8`

加上google DNS

```
[URL Rewrite]
^http://www.google.cn https://www.google.com 302
```

这条规则可以让safari使用google作为默认搜索引擎了 可以直接在地址栏和spotlight里搜索关键字

另外建议surge conf里也加上更新的日期

**Comment by huanz** [comment]
好的，感谢建议，我回头处理下

via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=9.1.21&pv=10.0.2&source=email_footer_2]
On 周五, 10月 14, 2016 at 17:52, alex notifications@github.com wrote:
#!MANAGED-CONFIG
http://surge.w3cboy.com/CMCC.conf interval=86400

Surge 现在支持远程自动更新config了 86400表示间隔24小时更新一次

dns-server = 8.8.4.4, 8.8.8.8

加上google DNS

[URL Rewrite]
^http://www.google.cn https://www.google.com 302

这条规则可以让safari使用google作为默认搜索引擎了 可以直接在地址栏和spotlight里搜索关键字

另外建议surge conf里也加上更新的日期

**Comment by huanz** [comment]
已加

**Comment by ChengLuffy** [comment]
`strict=true` 建议增加这个参数，没有的话在手动更新后之后可能出现不自动更新的场景

---

更新：发现 在 `#UPDATE:2016-xxxxx`这一行存在时自动更新会失败

**Comment by huanz** [comment]
@ChengLuffy 
`#!MANAGED-CONFIG http://surge.w3cboy.com/CMCC.conf interval=86400 strict=true`
这样么？

关于自动更新的有相关文档么？

**Comment by ChengLuffy** [comment]
没有找到详细文档，只是从实际效果对比
![fullsizerender](https://cloud.githubusercontent.com/assets/15682381/19916728/f68834a8-a0f7-11e6-8681-f8019529e9a0.jpg)
上图中第一个是被人维护的比较简单的 `hosts` 文档，下面三个是您所维护的三份。
第一个 在⬅️滑之后点击 `update now` 显示更新时间，并的确定时更新。
二至四，在⬅️滑 点击 `update now` 后，就不显示更新时间，也没有定时更新。
在 `iCloud Drive` 删除 二至四 文档中 第一行 `#UPDATE:2016-xxxxx` 后同步至手机之后恢复。

**Comment by alexhua** [comment]
@huanz  抱歉之前提供的信息不充分，导致自动更新不起效。 @ChengLuffy 之前不能自动更新，以及手动更新后自动更新失效是因为 #!MANAGED-CONFIG http://surge.w3cboy.com/CMCC.conf interval=86400 没有放在conf文件的第一行。

官方文档在此https://manual.nssurge.com/others/managed-configuration.html

另外再提几条规则建议 
DOMAIN,h5.m.taobao.com,REJECT 这条影响淘宝和支付宝外卖正常登录和使用，建议去掉。
[rewrite] 建议增加 ^http://www.google.com.hk https://www.google.com.hk 302 优化google的使用

谢谢

**Comment by huanz** [comment]
@alexhua 感谢建议，已修改
