### ISSUE TITLE
为什么host路径里直接替换了，还是上不了

### ISSUE THREAD

**Issue by NetLogoclub** [huanz/surge-hosts#18]
我到googlehost项目库里下的host，到您这里下的，都上不了，什么原因，可以解答一下吗？

**Comment by gaoyuanning** [comment]
font{
        line-height: 1.7;
    }


    
买个代理用吧



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    
    
        font{
            line-height: 1.7;
        }
    
--Yuanning Gao (高远宁)Department of Computer Science and EngineeringShanghai Jiao Tong University-- 

                



    在2018年5月4日 10:36，NetLogoclub<notifications@github.com> 写道： 


我到googlehost项目库里下的host，到您这里下的，都上不了，什么原因，可以解答一下吗？

**Comment by huanz** [comment]
@NetLogoclub 可能是过期了，建议时常更新
