### ISSUE TITLE
建议对 Hosts 进行通配符匹配

### ISSUE THREAD

**Issue by yupolee** [huanz/surge-hosts#6]
感谢您对 Surge-hosts 的维护。

在我第一次下载 [CMCC.conf](https://github.com/huanz/surge-hosts/blob/master/CMCC.conf) 后，发现在约 3500 行 hosts 规则中，仅关于 Google 的 hosts 就有 2300 余条，这很浪费空间，也很没有效率。

Surge 的[Local DNS Mapping 文档](https://manual.nssurge.com/dns/local-dns-mapping.html)中写道：

> You can use * prefix to wildcard all sub-domains. Please note that Surge uses a simple string match. For example, *google.com will match google.com, foo.google.com and bargoogle.com. And *.google.com will **not** match google.com.

如果使用类似 `*google.com = 61.91.161.217` 的规则，可大幅缩短 conf 文件的行数，减小 conf 文件的体积，从而显著提升配置文件的运行效率。

如果有空的话，请您如此修正 conf 文件，感谢。

**Comment by huanz** [comment]
@Sunshycheer 配置文件的大小应该不会影响运行效率，surge配置的查找应该不是每次遍历查找，另外精确匹配的效率应该高于模糊匹配。不过这里我只是猜测，具体的会不会影响还得看作者的实现逻辑了。

**Comment by huanz** [comment]
@Sunshycheer 你可以对此

**Comment by yupolee** [comment]
@huanz 是我表述不当，配置文件过大可能会影响 Surge 的稳定性。
iOS network extension app 只能使用最多 6MB 的内存。以前因为配置文件过大遇到无法启动的 bug 。
不过目前来看，iOS 端使用这个配置后暂时运行良好，可能还不必进行精简。
