### ISSUE TITLE
你好，好像看不了youtube

### ISSUE THREAD

**Issue by yfnok** [huanz/surge-hosts#7]
非常感谢分享
但是威锋论坛别人分享的可以看 youtube
这个是他的分享的地址：http://bbs.feng.com/read-htm-tid-11095880.html

**Comment by huanz** [comment]
@yfnok 他的的host里面google是用的自己搭建的服务：

```
youtube.com = 203.210.7.38
www.youtube.com = 203.210.7.38
```

你可以访问这个ip看下，并非Google官方服务器，不担心个人隐私的话可用使用
