### ISSUE TITLE
surge说托管是啥意思啊

### ISSUE THREAD

**Issue by ghost** [huanz/surge-hosts#9]
自动更新吗？还是咋地
占用流量吗？

**Comment by huanz** [comment]
@lupin92 自动更新surge的配置文件

**Comment by ghost** [comment]
@huanz 
那是不是一直处于检测更新中
这样占不占内存  耗不耗流量

**Comment by huanz** [comment]
@lupin92 耗流量，配置文件很小的，基本上也耗费不了多少流量啊。每天更新一次，当然你也可以设置它多久更新一次：`#!MANAGED-CONFIG http://surge.w3cboy.com/CMCC.conf interval=86400`，`interval`即为多久更新

**Comment by ghost** [comment]
哇哦   可以哦   不错 哦  原来是这样啊   谢谢哈
